---
title: "biostat 273 - pubg"
author: "Landi Luo"
date: "12/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages:
```{r, message=FALSE}
if (!require("pacman"))  
  install.packages("pacman", repos = "http://cran.us.r-project.org/")
p_load("tidyverse", "GGally", "caret", "glmnet", "randomForest", "xgboost")
```

Read in data:
```{r}
# setwd("~/Documents/BIOSTAT 273")
train_solo <- readRDS(file = "train_solo.rds")
#test_solo <- readRDS(file = "test_solo.rds")
```

```{r}
# drop Id
train_solo <- select(train_solo, -Id)
```

## Correlation Matrix
```{r}
ggcorr(train_solo, hjust = 0.9, size = 3, color = "grey50",
       label = TRUE, label_size = 2, layout.exp = 3)
```

Split `train_solo` data into training and validation sets
```{r}
set.seed(3456)
trainIndex <- createDataPartition(train_solo$winPlacePerc, p = .8, list = FALSE, times = 1)
head(trainIndex)

pubgTrain <- train_solo[ trainIndex, ]
pubgTest  <- train_solo[-trainIndex, ]
```


## OLS Regression
```{r}
mod_ols <- lm(winPlacePerc ~ ., data = pubgTrain)
mod_ols$coefficients

pred_ols <- predict.lm(mod_ols, pubgTest)

confine_predictions = function(x){
  x = ifelse(x > 1, 1, x)
  x = ifelse(x < 0, 0, x)
}
 
pred_ols <- confine_predictions(pred_ols)

#error <- pubgTest$winPlacePerc - pred_ols
#mean(abs(error))
# sqrt(mean(error^2)) # rmse is 0.097

# MAE
postResample(pred_ols, pubgTest$winPlacePerc)
```
The mean absolute error is `r mae`.

## Ridge Regression 1
```{r}
# define predictors and outcome
grep("winPlacePerc", colnames(pubgTrain))
x_train = model.matrix(winPlacePerc ~ ., data = pubgTrain)[ ,-16]
y_train = pubgTrain$winPlacePerc

x_test = model.matrix(winPlacePerc ~ ., data = pubgTest)[ ,-16]
y_test = pubgTest$winPlacePerc

# cross validation for optimal lambda
cv_fit <- cv.glmnet(x_train, y_train, alpha = 0)
opt_lambda <- cv_fit$lambda.min 
opt_lambda

#grid = 10^seq(10, -2, length = 100)
grid <- 10^seq(3, -2, by = -.1)
mod_ridge <- glmnet(x_train, y_train, alpha = 0, lambda = grid, thresh = 1e-12)
pred_ridge <- predict(mod_ridge, s = opt_lambda, newx = x_test) %>% confine_predictions()

# MAE
postResample(pred_ridge, y_test)
```

## Ridge Regression 2
```{r}
train_predictors <- select(pubgTrain, -winPlacePerc)
test_predictors <- select(pubgTest, -winPlacePerc)

lambdas <- 10^seq(3, -2, by = -.1)

# Define training variables and outcome variable
x = train_predictors %>% data.matrix()
y = pubgTrain$winPlacePerc

## Cross Validation to get optimal lambda for ridge regression
cv_fit = cv.glmnet(x, y, alpha = 0, lambda = lambdas)
opt_lambda = cv_fit$lambda.min

m_ridge = glmnet(x, y, alpha = 0, lambda = opt_lambda)
# Predict using held out test variables and outcome variable
p_ridge = cbind(rep(1, nrow(pubgTest)), test_predictors) %>% as.matrix %*% 
          as.matrix(coef(m_ridge)) %>% confine_predictions()

colnames(p_ridge) = c("p_ridge")

postResample(p_ridge, pubgTest$winPlacePerc)
```

## Lasso Regression
```{r}
## Cross Validation to get optimal lambda for lasso regression
cv_fit = cv.glmnet(x, y, alpha = 1, lambda = lambdas)
opt_lambda = cv_fit$lambda.min

m_ridge = glmnet(x, y, alpha = 1, lambda = opt_lambda)
# Predict using held out test variables and outcome variable
p_ridge = cbind(rep(1, nrow(pubgTest)), test_predictors) %>% as.matrix %*% 
          as.matrix(coef(m_ridge)) %>% confine_predictions()

colnames(p_ridge) = c("p_ridge")

postResample(p_ridge, pubgTest$winPlacePerc)
```

## Random Forest
```{r}
train_predictors <- select(pubgTrain, -winPlacePerc)
test_predictors <- select(pubgTest, -winPlacePerc)
m_forest_100 = randomForest(train_predictors, pubgTrain$winPlacePerc, ntree = 100, do.trace = TRUE)
m_forest_250 = randomForest(train_predictors, pubgTrain$winPlacePerc, ntree = 250, do.trace = TRUE)
m_forest_500 = randomForest(train_predictors, pubgTrain$winPlacePerc, ntree = 500, do.trace = TRUE)

p_forest = predict(m_forest_500, train_predictors)
postResample(p_forest, pubgTest$winPlacePerc)
```

## Boosting
```{r}
m_boost = xgboost(as.matrix(train_predictors), pubgTrain$winPlacePerc, nrounds = 100)
p_boost = predict(m_boost, as.matrix(test_predictors)) %>% confine_predictions
#MAE(p_boost, pubgTest$winPlacePerc)

postResample(p_boost, pubgTest$winPlacePerc)
```
