---
title: "pubg"
author: "Lumi Huang"
date: "12/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
setwd(".")
pubg_tr <- read_csv("./all/train_V2.csv")
```
drop missing value
```{r}
pubg_tr <- pubg_tr %>% drop_na()
```

filter duo
```{r}
pubg_tr <- pubg_tr %>%
  filter(matchType == 'duo'| matchType == 'normal-duo-fpp' | 
           matchType == 'normal-duo' | matchType == 'duo-fpp')
nrow(pubg_tr)
```

```{r}
#modify the winpoint and kill point based on rank point
pubg_tr$winPoints = ifelse(pubg_tr$winPoints == 0 & pubg_tr$rankPoints != -1, NA, pubg_tr$winPoints)
pubg_tr$killPoints = ifelse(pubg_tr$killPoints == 0 & pubg_tr$rankPoints != -1, NA, pubg_tr$killPoints)


```

```{r}
pubg_group <- pubg_tr %>%
  select(Id, groupId, matchId, assists, boosts, damageDealt, DBNOs, headshotKills,
         heals, killPlace, killPoints, kills, killStreaks, longestKill, maxPlace, numGroups,
         revives, rideDistance, roadKills, swimDistance, teamKills, vehicleDestroys, walkDistance,
         weaponsAcquired, winPoints, winPlacePerc, matchDuration) %>%
  distinct() %>%
  group_by(matchId, groupId) %>%
  summarise(teamsize = n(), assists = sum(assists, na.rm = TRUE),
            boosts = sum(boosts, na.rm = TRUE), damageDealt = sum(damageDealt, na.rm = TRUE), 
            DBNOs = sum(DBNOs, na.rm = TRUE), headshotKills = sum(headshotKills, na.rm = TRUE),
            heals = sum(heals, na.rm = TRUE), killPlace = sum(killPlace, na.rm = TRUE), 
            killPoints = ifelse(is.finite(max(killPoints, na.rm = TRUE)), max(killPoints), NA),
            kills = sum(kills, na.rm = TRUE), 
            killStreaks = mean(killStreaks, na.rm = TRUE), longestKill = mean(longestKill, na.rm = TRUE),
            maxPlace = max(maxPlace, na.rm = TRUE), numGroups = mean(numGroups, na.rm = TRUE), 
            revives = sum(revives, na.rm = TRUE), rideDistance = max(rideDistance, na.rm = TRUE), 
            roadKills = sum(roadKills, na.rm = TRUE), swimDistance = max(swimDistance, na.rm = TRUE),
            teamKills = sum(teamKills, na.rm = TRUE), vehicleDestroys = sum(vehicleDestroys, na.rm = TRUE), 
            walkDistance = max(walkDistance, na.rm = TRUE), 
            weaponsAcquired = sum(weaponsAcquired, na.rm = TRUE), 
            matchDuration = mean(matchDuration, na.rm = TRUE),
            winPoints = ifelse(is.finite(max(winPoints, na.rm = TRUE)), max(winPoints), NA),
            winPlacePerc = mean(winPlacePerc, na.rm = TRUE))
nrow(pubg_group)
```

```{r}
pubg_group <- pubg_group %>% 
  filter(teamsize <= 2)
nrow(pubg_group)
```

```{r}
pubg_group <- pubg_group %>%
  mutate(KADistance = (kills + assists)/walkDistance, 
         KADuration = (kills + assists)/matchDuration,
         KillstreaksperKills = killStreaks/kills,
         itemDuration = (boosts + heals + weaponsAcquired)/matchDuration,
         itemDistance = (boosts + heals + weaponsAcquired)/walkDistance)
```

```{r}
write_csv(pubg_group, "./all/train_group.csv")
```

